[package]
name = "ga_v4_flattener"
version = "0.1.0"
authors = ["Charlie Saunders <charlieasaunders@gmail.com>"]

[dependencies]
failure = "0.1.2"
failure_derive = "0.1.2"
joinery = "1.0.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
